### ISSUE TITLE
Can't configure Input Devices in Setup.

### ISSUE THREAD

**Issue by stank2k** [sacredbanana/lab3d-sdl#2]
Version: [Kens-Labyrinth-Windows-x86.zip](https://github.com/sacredbanana/lab3d-sdl/releases/download/4.1.4/Kens-Labyrinth-Windows-x86.zip)
OS: Windows 10

Select "Setup"
Select "Configure Input"
Select an input.
Select Movement/Weapons/Action

Curser goes back to main setup screen.

**Comment by sacredbanana** [comment]
Thanks for the report. I will look into this. And sorry for the delay.

**Comment by sacredbanana** [comment]
This is now fixed in the new 4.1.5 release. Sorry again about the delay. I honestly never saw it until a few days ago. I'll be more diligent with my GitHub notifications from now on.
