### ISSUE TITLE
Latest Switch version doesn't work (buttons)

### ISSUE THREAD

**Issue by JrRadiant** [sacredbanana/lab3d-sdl#5]
Hi, thank you for the port!

Unfortunately, in the latest Switch release [4.1.5 (2024-02-03) 96fc71d on latest Switch FW no buttons works, at all. The game starts, it's menu shows but absolutely 0 buttons works, except the HOME button, here:
![scr (8)](https://github.com/sacredbanana/lab3d-sdl/assets/61790774/ed4196b0-ee6e-4c5a-b7d5-ae8322fe7e27)

Please fix it., so rn the Switch version is completely unplayable :)

**Comment by sacredbanana** [comment]
Thanks for the report. What firmware version are you using?

**Comment by JrRadiant** [comment]
Tried two versions, 17.0.1 and 18.0.0, in both not working.

**Comment by sacredbanana** [comment]
Ok thanks. My Switch firmware is only at 6.0.0 and it works on that firmware. I'll create an emuNAND and upgrade to 18.0.0 and try to get Ken's Labyrinth working for the latest firmware

**Comment by sacredbanana** [comment]
By the way, in the meantime you could try putting your Switch in its Dock and plugging in a USB keyboard. I added support for USB devices a while ago. See if that works

**Comment by sacredbanana** [comment]
Just replicated the issue. This is unacceptable. I will work on a fix.

**Comment by JrRadiant** [comment]
I will wait, thank you!

**Comment by sacredbanana** [comment]
I fixed joycons in the new 1.4.6 release <3

Enjoy!

https://github.com/sacredbanana/lab3d-sdl/releases/tag/4.1.6

**Comment by JrRadiant** [comment]
Thank you very much!
