### ISSUE TITLE
General MIDI option doesn't work at all

### ISSUE THREAD

**Issue by atalarikt99** [sacredbanana/lab3d-sdl#6]
Choosing this option will result in all music playback being disabled (despite ksmmidi.txt already available within the folder). Starting any game will further result in a crash.
![image](https://github.com/sacredbanana/lab3d-sdl/assets/22086197/686cdeb6-7412-46d0-9ba4-1c7fa46aa1f1)

**Comment by sacredbanana** [comment]
Thanks for the report. Just made a new release with a fix for MIDI. Go try out 4.1.8 :)

**Comment by atalarikt99** [comment]
Thanks! 2.1 works like a charm, but 1.1 for some reason plays what sounds like a white noise while also crashing. Probably only a one-time error though, as my second attempt has no issue so far when I was writing this.

**Comment by sacredbanana** [comment]
Hm, raise another issue if you can get it to reliably crash. The Windows build playing KL 1.1 isn't crashing for me at all

**Comment by atalarikt99** [comment]
Wait, while I was trying 2.1 again the crash also happened to it. Not sure what exactly takes, but this happens at times while sometimes it just works flawlessly for both 1.1 and 2.1.
The crash usually happens while the game is loading graphics on 1.1. Unsurprisingly, 2.1 is much more stable on my end, but the crash happened twice there, I can recall.
![image](https://github.com/sacredbanana/lab3d-sdl/assets/22086197/bf87c756-57e0-4d0f-8a91-25c5c9ee45f8)

**Comment by sacredbanana** [comment]
Does it crash on both the 32 and 64 bit version?

**Comment by atalarikt99** [comment]
Yes, both versions contain this crash.

Also, on an unrelated side note, given that you got the KSM files to play with General MIDI instead of only OPL emulation, is there any way to convert the KSM files into MID files directly? Asking out of curiosity.
